version: "3"

x-var: &USER_NAME
  "user"
x-var: &USER_PASSWORD
  "password123"
x-var: &ADMIN_PASSWORD
  "This_password_is_very*3_strong_password_!"

services:
#database
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    #container_name: "mysql57"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: *ADMIN_PASSWORD
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: *USER_NAME
      MYSQL_PASSWORD: *USER_PASSWORD

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"


#application
  wordpress:
    image: wordpress:latest
    #container_name: "wordpress"
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: *USER_NAME
      WORDPRESS_DB_PASSWORD: *USER_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #container_name: "phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80

  ftp:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    restart: always
    volumes: 
      - "/contents/ftpserver/user:/home/user"
      - "/contents/ftpserver/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: *USER_NAME
      FTP_USER_PASS: *USER_PASSWORD
      FTP_USER_HOME: /home/user

  dns:
    image: sameersbn/bind:9.16.1-20200524
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    restart: always
    volumes:
    - /contents/bind:/data
    
  dns2:
    image: jpillora/dnsmasq
    ports:
    - "10053:53/udp"
    - "5380:8080"
    restart: always
    volumes: 
      - "./contents/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf"
    environment:
      HTTP_USER: *USER_NAME
      HTTP_PASS: *USER_PASSWORD