version: "3"

x-var: &USER_NAME
  "user"
x-var: &USER_PASSWORD
  "password123"
x-var: &ADMIN_PASSWORD
  "This_password_is_very*3_strong_password_!"

services:
#database
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    #container_name: "mysql57"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: *ADMIN_PASSWORD
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: *USER_NAME
      MYSQL_PASSWORD: *USER_PASSWORD


#application
  wordpress:
    image: wordpress:latest
    #container_name: "wordpress"
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: *USER_NAME
      WORDPRESS_DB_PASSWORD: *USER_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #container_name: "phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80

  ftp:
    image: stilliard/pure-ftpd
    ports:
      - 21:21
      - 30000-30010:30000-30010
    restart: always
    network_mode: host
    volumes: 
      - ./contents/ftpserver:/home/user
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: *USER_NAME
      FTP_USER_PASS: *USER_PASSWORD
      FTP_USER_HOME: /home/user




